ignoredBuiltDependencies:
  - '@swc/core'
  - better-sqlite3
  - core-js-pure
  - esbuild
  - sharp

onlyBuiltDependencies:
  - '@swc/core'
  - better-sqlite3
  - core-js-pure
  - esbuild
  - sharp

patchedDependencies:
  '@strapi/admin@5.39.0': patches/@strapi__admin@5.39.0.patch
