/**
 * Spanish labels for every field in the Content Manager, keyed by content type
 * or component UID. Editors see these instead of the raw attribute names.
 *
 * The help text under each field comes from the attribute `description` in
 * the schema JSON files. `tests/admin-labels.test.ts` fails when a schema
 * field has no label here, so new fields must be added to this map.
 */
export const FIELD_LABELS: Record<string, Record<string, string>> = {
  'api::category.category': {
    name: 'Nombre',
    slug: 'Identificador en la URL (slug)',
    color: 'Color',
    order: 'Orden',
    listings: 'Lugares y experiencias',
  },
  'api::community-member.community-member': {
    name: 'Nombre completo',
    slug: 'Identificador en la URL (slug)',
    role: 'Rol u oficio',
    bio: 'Biografía',
    pullQuote: 'Cita destacada',
    photo: 'Foto',
    gallery: 'Galería de imágenes',
    contact: 'Contacto',
    listings: 'Lugares y experiencias',
    relatedMembers: 'Personas relacionadas',
    legacyNote: 'Nota interna (no pública)',
    isFeatured: '¿Es destacada?',
    order: 'Orden',
    community: 'Comunidad',
    shortDescription: 'Descripción corta',
  },
  'api::community.community': {
    name: 'Nombre',
    slug: 'Identificador en la URL (slug)',
    tagline: 'Frase de cabecera',
    description: 'Descripción',
    order: 'Orden',
    color: 'Color principal',
    textColor: 'Color de texto',
    badgeIcon: 'Insignia (icono)',
    heroImage: 'Imagen de cabecera',
    location: 'Ubicación',
    googleMapsUrl: 'Enlace de Google Maps',
    historyHeader: 'Historia: encabezado',
    historyMilestones: 'Historia: línea de tiempo',
    historyText: 'Historia: texto',
    touristMapImage: 'Mapa turístico: imagen',
    touristMapCaption: 'Mapa turístico: pie de imagen',
    highlightsHeader: 'Destacados: encabezado',
    highlights: 'Destacados: tarjetas',
    quickFactsHeader: 'Datos rápidos: encabezado',
    quickFacts: 'Datos rápidos',
    gallery: 'Galería de imágenes',
    finalCta: 'Llamada a la acción final',
    listings: 'Lugares y experiencias',
    members: 'Personas de la comunidad',
  },
  'api::good-practices-page.good-practices-page': {
    internalLabel: 'Etiqueta interna',
    hero: 'Cabecera (hero)',
    intro: 'Introducción',
    protectedArea: 'Área natural protegida',
    anpMapImage: 'Mapa del ANP',
    conanpUrl: 'Enlace a la CONANP',
    influenceHeader: 'Área de influencia: encabezado',
    influenceText: 'Área de influencia: texto',
    fishingHeader: 'Refugio pesquero: encabezado',
    fishingText: 'Refugio pesquero: texto',
    fishingRules: 'Refugio pesquero: reglas',
    fishingRefugeMapImage: 'Refugio pesquero: mapa',
    recommendationsHeader: 'Recomendaciones: encabezado',
    recommendations: 'Recomendaciones',
    tipsHeader: 'Consejos: encabezado',
    tips: 'Consejos',
    campaign: 'Bloque de campaña',
    finalCta: 'Llamada a la acción final',
  },
  'api::homepage.homepage': {
    internalLabel: 'Etiqueta interna',
    hero: 'Carrusel principal (hero)',
    highlightsHeader: 'Destacados: encabezado',
    highlights: 'Destacados: tarjetas',
    quickFactsHeader: 'Datos rápidos: encabezado',
    quickFacts: 'Datos rápidos',
    quickFactsImage1: 'Datos rápidos: imagen 1',
    quickFactsImage2: 'Datos rápidos: imagen 2',
    mapSection: 'Sección de mapa',
    finalCta: 'Llamada a la acción final',
    regionMapImage: 'Mapa de la región',
  },
  'api::legal-page.legal-page': {
    slug: 'Identificador en la URL (slug)',
    title: 'Título',
    content: 'Contenido',
  },
  'api::listing.listing': {
    title: 'Nombre',
    slug: 'Identificador en la URL (slug)',
    shortDescription: 'Descripción corta',
    description: 'Descripción completa',
    mainImage: 'Imagen principal',
    gallery: 'Galería de imágenes',
    logo: 'Logotipos',
    price: 'Precio',
    isFeatured: '¿Es destacado?',
    order: 'Orden',
    category: 'Categoría',
    tags: 'Etiquetas',
    contact: 'Contacto',
    location: 'Ubicación',
    schedule: 'Horario',
    amenities: 'Servicios e incluidos',
    recommendations: 'Recomendaciones',
    relatedListings: 'Lugares relacionados',
    members: 'Personas de la comunidad',
    stories: 'Historias',
    products: 'Productos o servicios',
    community: 'Comunidad',
    hideContact: 'Ocultar contacto',
  },
  'api::site-content.site-content': {
    key: 'Clave (identificador)',
    title: 'Título',
    text: 'Texto',
    order: 'Orden',
    extraData: 'Datos adicionales (JSON)',
  },
  'api::site-global.site-global': {
    contactEmail: 'Contacto: correo',
    contactPhone: 'Contacto: teléfono',
    contactPhoneRaw: 'Contacto: teléfono sin formato',
    contactWhatsapp: 'Contacto: WhatsApp',
    contactAddress: 'Contacto: dirección',
    socialInstagram: 'Redes: Instagram',
    socialFacebook: 'Redes: Facebook',
    socialGoogleMaps: 'Redes: Google Maps',
    metadataSiteName: 'SEO: nombre del sitio',
    metadataDefaultTitle: 'SEO: título por defecto',
    metadataDefaultDescription: 'SEO: descripción por defecto',
    seoKeywords: 'SEO: palabras clave',
    seoOgImage: 'SEO: imagen para compartir',
    seoOgUrl: 'SEO: URL canónica',
    seoAuthor: 'SEO: autor',
    seoThemeColor: 'SEO: color del tema',
    logoImage: 'Logotipo',
    logoShortName: 'Nombre corto',
  },
  'amenity.amenity-item': {
    label: 'Nombre',
    content: 'Descripción',
  },
  'campaign.campaign-block': {
    title: 'Título',
    description: 'Descripción',
    logo: 'Logotipo',
    url: 'Enlace',
    linkLabel: 'Texto del enlace',
  },
  'contact.contact-info': {
    phoneCountryCode: 'Teléfono: código de país',
    phoneNumber: 'Teléfono: número',
    whatsappCountryCode: 'WhatsApp: código de país',
    whatsappNumber: 'WhatsApp: número',
    email: 'Correo electrónico',
    instagram: 'Instagram',
    facebook: 'Facebook',
    tiktok: 'TikTok',
    website: 'Sitio web',
  },
  'cta.cta-section': {
    title: 'Título',
    description: 'Descripción',
    buttonLabel: 'Texto del botón',
    buttonLink: 'Enlace del botón',
  },
  'guide.milestone': {
    year: 'Año',
    text: 'Descripción',
  },
  'guide.protected-link': {
    title: 'Título',
    text: 'Descripción',
    linkLabel: 'Texto del enlace',
    linkHref: 'Enlace',
  },
  'guide.text-list-item': {
    text: 'Texto',
  },
  'hero.hero-section': {
    title: 'Título',
    titleHighlight: 'Parte resaltada del título',
    description: 'Descripción',
    ctaLabel: 'Texto del botón',
    ctaLink: 'Enlace del botón',
    images: 'Imágenes del carrusel',
  },
  'highlight.highlight-card': {
    title: 'Título',
    description: 'Descripción',
    image: 'Imagen',
    link: 'Enlace',
  },
  'location.geo-point': {
    geoPoint: 'Punto en el mapa',
  },
  'map.map-section': {
    title: 'Título',
    description: 'Descripción',
    buttonLabel: 'Texto del botón',
    buttonUrl: 'Enlace del botón',
    image: 'Imagen de respaldo',
    centerPoint: 'Centro del mapa',
    zoom: 'Nivel de zoom',
  },
  'product.item': {
    name: 'Nombre',
    description: 'Descripción',
  },
  'quickfact.quick-fact': {
    title: 'Título',
    value: 'Valor',
    description: 'Descripción',
  },
  'recommendation.recommendation-item': {
    label: 'Título',
    description: 'Descripción',
  },
  'schedule.hours': {
    text: 'Horario',
  },
  'section.section-header': {
    title: 'Título',
    subtitle: 'Subtítulo',
  },
  'story.story-block': {
    title: 'Título',
    narrative: 'Narración',
    highlightQuote: 'Cita destacada',
    era: 'Época o año',
    theme: 'Tema',
    storyteller: 'Narrador(a)',
    image: 'Imagen',
    gallery: 'Galería de imágenes',
  },
  'tag.tag-item': {
    label: 'Texto de la etiqueta',
  },
};
